------------------------------ (1). NULL/BLANK VALUES

				SELECT
					SUM(CASE WHEN AGE IS NULL THEN 1 ELSE 0 END) AS 'NULL_SAL',
					SUM(CASE WHEN DAILYRATE IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN DISTANCEFROMHOME IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN EDUCATION IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN EMPLOYEECOUNT IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN EMPLOYEENUMBER IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN ENVIRONMENTSATISFACTION IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN HOURLYRATE IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN JOBINVOLVEMENT IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN JOBLEVEL IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN JOBSATISFACTION IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN MONTHLYINCOME IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN MONTHLYRATE IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN NUMCOMPANIESWORKED IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN PERCENTSALARYHIKE IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN PERFORMANCERATING IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN RELATIONSHIPSATISFACTION IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN STANDARDHOURS IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN STOCKOPTIONLEVEL IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN TOTALWORKINGYEARS IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN TRAININGTIMESLASTYEAR IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN WORKLIFEBALANCE IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN YEARSATCOMPANY IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN YEARSINCURRENTROLE IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN YEARSSINCELASTPROMOTION IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT',
					SUM(CASE WHEN YEARSWITHCURRMANAGER IS NULL THEN 1 ELSE 0 END) AS 'NULL_DEPT'
				FROM IBM_HR_ANALYSIS;


				SELECT 
					SUM(CASE WHEN ATTRITION = '' THEN 1 ELSE 0 END) AS 'BLANK',
					SUM(CASE WHEN BUSINESSTRAVEL = '' THEN 1 ELSE 0 END) AS 'BLANK',
					SUM(CASE WHEN EDUCATIONFIELD = '' THEN 1 ELSE 0 END) AS 'BLANK',
					SUM(CASE WHEN GENDER = '' THEN 1 ELSE 0 END) AS 'BLANK',
					SUM(CASE WHEN JOBROLE = '' THEN 1 ELSE 0 END) AS 'BLANK',
					SUM(CASE WHEN MARITALSTATUS = '' THEN 1 ELSE 0 END) AS 'BLANK',
					SUM(CASE WHEN OVER18 = '' THEN 1 ELSE 0 END) AS 'BLANK',
					SUM(CASE WHEN OVERTIME = '' THEN 1 ELSE 0 END) AS 'BLANK'

				FROM IBM_HR_ANALYSIS
			
					
---------------------------- NO NULL VALUES OR BLANK VALUES IN THE DATASET
SELECT * FROM IBM_HR_ANALYSIS



---------------------------- (2). CHANGING COLUMN NAMES
EXEC SP_RENAME 'IBM_HR_ANALYSIS.BUSINESSTRAVEL', 'BUSINESS_TRAVEL', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.DAILYRATE', 'DAILY_RATE', 'COLUMN'

EXEC SP_RENAME 'IBM_HR_ANALYSIS.AGE', 'AGE', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.ATTRITION', 'ATTRITION', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.DEPARTMENT', 'DEPARTMENT', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.DISTANCEFROMHOME', 'DISTANCE_FROM_HOME', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.EDUCATION', 'EDUCATION', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.EDUCATIONFIELD', 'EDUCATION_FIELD', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.EMPLOYEECOUNT', 'EMPLOYEE_COUNT', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.EMPLOYEENUMBER', 'EMPLOYEE_NUMBER', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.ENVIRONMENTSATISFACTION', 'ENVIRONMENT_SATISFACTION', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.GENDER', 'GENDER', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.HOURLYRATE', 'HOURLY_RATE', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.JOBINVOLVEMENT', 'JOB_INVOLVEMENT', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.JOBLEVEL', 'JOB_LEVEL', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.JOBROLE', 'JOB_ROLE', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.JOBSATISFACTION', 'JOB_SATISFACTION', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.MARITALSTATUS', 'MARITAL_STATUS', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.MONTHLYINCOME', 'MONTHLY_INCOME', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.MONTHLYRATE', 'MONTHLY_RATE', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.NUMCOMPANIESWORKED', 'NUM_COMPANIES_WORKED', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.OVER18', 'OVER_18', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.OVERTIME', 'OVER_TIME', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.PERCENTSALARYHIKE', 'PERCENT_SALARY_HIKE', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.PERFORMANCERATING', 'PERFORMANCE_RATING', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.RELATIONSHIPSATISFACTION', 'RELATIONSHIP_SATISFACTION', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.STANDARDHOURS', 'STANDARD_HOURS', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.STOCKOPTIONLEVEL', 'STOCK_OPTION_LEVEL', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.TOTALWORKINGYEARS', 'TOTAL_WORKING_YEARS', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.TRAININGTIMESLASTYEAR', 'TRAINING_TIMES_LAST_YEAR', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.WORKLIFEBALANCE', 'WORK_LIFE_BALANCE', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.YEARSATCOMPANY', 'YEARS_AT_COMPANY', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.YEARSINCURRENTROLE', 'YEARS_IN_CURRENT_ROLE', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.YEARSSINCELASTPROMOTION', 'YEARS_SINCE_LAST_PROMOTION', 'COLUMN'
EXEC SP_RENAME 'IBM_HR_ANALYSIS.YEARSWITHCURRMANAGER', 'YEARS_WITH_CURR_MANAGER', 'COLUMN'




SELECT * FROM IBM_HR_ANALYSIS



---------------------------- (3). CHECKING DATATYPE FOR COULMNS
					SELECT * FROM IBM_HR_ANALYSIS

					SELECT 
						COLUMN_NAME, 
						DATA_TYPE, 
						CHARACTER_MAXIMUM_LENGTH
					FROM 
						INFORMATION_SCHEMA.COLUMNS
					WHERE 
						TABLE_NAME = 'IBM_HR_ANALYSIS'





---------------------------- (4). CHANGING DATATYPE FOR COULMNS

AGE, DAILY_RATE, DISTANCE_FROM_HOME, EDUCATION, EMPLOYEE_COUNT, EMPLOYEE_NUMBER, ENVIRONMENT_SATISFACTION, HOURLY_RATE, 
JOB_INVOLVEMENT, JOB_LEVEL, JOB_SATISFACTION, MONTHLY_INCOME, MONTHLY_RATE, NUM_COMPANIES_WORKED, PERCENT_SALARY_HIKE,
PERFORMANCE_RATING, RELATIONSHIP_SATISFACTION, STANDARD_HOURS, STOCK_OPTION_LEVEL, TOTAL_WORKING_YEARS, 
TRAINING_TIMES_LAST_YEAR, WORK_LIFE_BALANCE, YEARS_AT_COMPANY, YEARS_IN_CURRENT_ROLE, YEARS_SINCE_LAST_PROMOTION, 
YEARS_WITH_CURR_MANAGER


ALTER TABLE IBM_HR_ANALYSIS
ALTER COLUMN YEARS_WITH_CURR_MANAGER INT 		 
					 
	

---------------------------- (5). CHECKING DUPLICATES
					SELECT *, COUNT(*) AS 'DUP_COUNT'
					FROM IBM_HR_ANALYSIS
					GROUP BY AGE, ATTRITION, BUSINESS_TRAVEL, DAILY_RATE, DEPARTMENT, DISTANCE_FROM_HOME, EDUCATION, EDUCATION_FIELD, 
					EMPLOYEE_COUNT, EMPLOYEE_NUMBER, ENVIRONMENT_SATISFACTION, GENDER, HOURLY_RATE, 
					JOB_INVOLVEMENT, JOB_LEVEL, JOB_ROLE,  JOB_SATISFACTION, MARITAL_STATUS, MONTHLY_INCOME, MONTHLY_RATE, 
					NUM_COMPANIES_WORKED, OVER_18, OVER_TIME, PERCENT_SALARY_HIKE, 
					PERFORMANCE_RATING, RELATIONSHIP_SATISFACTION, STANDARD_HOURS, STOCK_OPTION_LEVEL, TOTAL_WORKING_YEARS, 
					TRAINING_TIMES_LAST_YEAR, WORK_LIFE_BALANCE, YEARS_AT_COMPANY, YEARS_IN_CURRENT_ROLE, YEARS_SINCE_LAST_PROMOTION, 
					YEARS_WITH_CURR_MANAGER
					HAVING COUNT(*)>1


---------------------------- NO DUPLICATE ROWS FOUND




---------------------------- (6). FIXING INCONSISTENT ENTRIES IN OVER_18 COLUMN
SELECT * FROM IBM_HR_ANALYSIS

					
					SELECT DISTINCT ENVIRONMENT_SATISFACTION FROM IBM_HR_ANALYSIS

					UPDATE IBM_HR_ANALYSIS SET OVER_18 = 'Yes'
					WHERE OVER_18 = 'Y'





---------------------------- (7). FIXING INCONSISTENT ENTRIES IN DEPARTMENT COLUMN
					
					SELECT DISTINCT DEPARTMENT FROM IBM_HR_ANALYSIS

					UPDATE IBM_HR_ANALYSIS SET DEPARTMENT = REPLACE(REPLACE(DEPARTMENT, ' ', '_'), '&', 'And')
					WHERE DEPARTMENT LIKE '% %' OR DEPARTMENT LIKE '&' 



---------------------------- (8). FIXING INCONSISTENT ENTRIES IN EDUCATION_FIELD COLUMN
					SELECT DISTINCT EDUCATION_FIELD FROM IBM_HR_ANALYSIS

					UPDATE IBM_HR_ANALYSIS SET EDUCATION_FIELD = REPLACE(EDUCATION_FIELD, ' ', '_')
					WHERE EDUCATION_FIELD LIKE '% %'



---------------------------- (9). FIXING INCONSISTENT ENTRIES IN JOB_ROLE COLUMN

					SELECT DISTINCT JOB_ROLE FROM IBM_HR_ANALYSIS

					UPDATE IBM_HR_ANALYSIS SET JOB_ROLE = REPLACE(JOB_ROLE, ' ', '_')
					WHERE JOB_ROLE LIKE '% %'


					SELECT * FROM IBM_HR_ANALYSIS



---------------------------- (10). FIXING INCONSISTENT ENTRIES IN OVER_TIME COLUMN
					
					SELECT DISTINCT OVER_TIME FROM IBM_HR_ANALYSIS
